#
# File:		Makefile
# Desctription:	Build simple TCP client and server
#

all:	client server bi_client bi_server

clean:
	rm -f *~ *.o client server bi_client bi_server

clobber:
	rm -f client server

