/* Header file generated by fdesign on Fri Mar  1 16:12:43 2024 */

#ifndef FD_digit_h_
#define FD_digit_h_

#include <forms.h>

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * digit;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * led1;
    FL_OBJECT * led2;
    FL_OBJECT * led3;
    FL_OBJECT * led4;
    FL_OBJECT * led5;
    FL_OBJECT * led6;
    FL_OBJECT * led7;
} FD_digit;

FD_digit * create_form_digit( void );

#endif /* FD_digit_h_ */
