/* Header file generated by fdesign on Fri Mar  1 16:12:43 2024 */

#ifndef FD_digit_h_
#define FD_digit_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

#define NCOL 7
#define NROW 9

#define PITCH 10

/* Forms and Objects */

typedef struct {
  FL_FORM   * digit;
  void      * vdata;
  char      * cdata;
  long        ldata;

  // array of 7x9 LEDs
  FL_OBJECT * leds[NCOL][NROW];
} FD_digit;

FD_digit * create_form_digit( void );

#endif /* FD_digit_h_ */
