M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-04-11T13:13:19-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-11T13:13:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X6.0Y-1.4
X6.0Y-4.1
X7.9Y-1.4
X7.9Y-4.1
M30
